# -*- coding: utf-8 -*-
"""Coding Loops Task 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g1HISXOGwiOHYBqFzBzIMG-BoDuLhYVP
"""

list1 = [12,-7,5,64,-14]
for x in list1:
 if x>=0:
  print(x)

list2 = [12,14,-95,3]
for x in list2:
  if x>=0:
    print(x)