# -*- coding: utf-8 -*-
"""Coding Loops Task 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iNRgHG_oXPD-geYtypzb1mOkmAHOtnFK
"""

nterms = int(input("how many terms?"))
n1, n2 = 0, 1
count  = 0
if nterms <= 0:
  print("please enter positve integer")
elif nterms == 1:
  print("fibonacci sequence upto",nterms,":")
  print(n1)
else:
  print("fibonacci sequence:")
  while count < nterms:
    print(n1)
    nth = n1 + n2
    n1 = n2
    n2 = nth
    count += 1

