# -*- coding: utf-8 -*-
"""Image Classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sbw3c6VDel7RnD-rdM3oPQzOd48DpxMH
"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

from google.colab import files
uploaded = files.upload()

#Load the MNIST dataset from CSV
mnist_data = pd.read_csv("mnist.csv.csv")

#seperate features (pixels) and labels
X = mnist_data.drop('label',axis=1)
y = mnist_data['label']

#split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

#initialize and train the Random Forest Classifier
rf_classifier = RandomForestClassifier(n_estimators=100,random_state=42)
rf_classifier.fit(X_train, y_train)

#predict labels for the test set
y_pred = rf_classifier.predict(X_test)

#calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:",accuracy)