# -*- coding: utf-8 -*-
"""Working with Data Structures.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mhds6lfOWPk_JEmYwLBpcVQ4BFdWoocX
"""

E = {0,2,4,6,8};
N = {1,2,3,4,5};

print ("union of E and N is:", E | N)
print ("intersection of E and N", E & N)
print ("difference of E and N", E - N)
print ("symmetric difference of E and N", E ^ N)